version: '3.8'

services:
  usuarios-servicio:
    build: ./usuario-servicio
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=default

  asignaturas-servicio:
    build: ./asignaturas-servicio
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=default

  matriculas-servicio:
    build: ./matriculas-servicio
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana

volumes:
  grafana-storage: