name: Pruebas Automatizadas

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-usuarios:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: usuario-servicio
    steps:
      - uses: actions/checkout@v3
      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Dar permisos a gradlew
        run: chmod +x ./gradlew
      - name: Ejecutar pruebas usuarios
        run: ./gradlew test

  test-asignaturas:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: asignaturas-servicio
    steps:
      - uses: actions/checkout@v3
      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Dar permisos a gradlew
        run: chmod +x ./gradlew
      - name: Ejecutar pruebas asignaturas
        run: ./gradlew test

  test-matriculas:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: matriculas-servicio
    steps:
      - uses: actions/checkout@v3
      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Dar permisos a gradlew
        run: chmod +x ./gradlew
      - name: Ejecutar pruebas matriculas
        run: ./gradlew test